# Análise de Dados

In [ ]:
# Importando biblioteca de análise de dados
import pandas as pd

In [3]:
# Importando base de dados

df = pd.read_csv('dados_alunos.csv')

In [6]:
# Verificar primeiras linhas do dataframe

df.head()

       nome  idade genero        curso  semestre  nota_final  faltas
0  Fernanda     22      F   Engenharia         7        8.85      21
1   Eduardo     28      M          ADS         1        6.49       9
2      Igor     24      M  Arquitetura         3        5.85       8
3      Igor     29      F  Arquitetura        10        5.65       7
4     Bruno     28      M  Arquitetura         7        8.64       5

In [ ]:
# Verificar últimas linhas do dataframe

df.tail()

       nome  idade genero        curso  semestre  nota_final  faltas
90     Igor     31      M  Arquitetura         6        9.16      15
91  Eduardo     26      F     Medicina         6        5.30       2
92     Igor     19      F   Engenharia         1        8.52      16
93   Helena     21      M          ADS        10        5.15      21
94     Igor     18      F   Engenharia         7        9.14      28
95   Helena     26      M          ADS         2        6.65      21
96   Carlos     20      F   Engenharia         8        9.33      24
97    Diana     27      M      Direito         1        9.31      17
98     Igor     27      F     Medicina         9        8.88      17
99   Carlos     22      F     Medicina         8        9.75      21

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   nome        100 non-null    str
 1   idade       100 non-null    int64
 2   genero      100 non-null    str
 3   curso       100 non-null    str
 4   semestre    100 non-null    int64
 5   nota_final  100 non-null    float64
 6   faltas      100 non-null    int64
dtypes: float64(1), int64(3), str(3)
memory usage: 5.6 KB

In [12]:
df[['nota_final', 'curso']]

    nota_final        curso
0         8.85   Engenharia
1         6.49          ADS
2         5.85  Arquitetura
3         5.65  Arquitetura
4         8.64  Arquitetura
..         ...          ...
95        6.65          ADS
96        9.33   Engenharia
97        9.31      Direito
98        8.88     Medicina
99        9.75     Medicina

[100 rows x 2 columns]